version: "3.3"
services:
  # 追記
  web:
    image: nginx:1.18-alpine
    ports:
      - 10085:85

    volumes:
      - ./Build/:/var/www/public/Build
      - ./TemplateData:/var/www/public/TemplateData
      - ./index.html:/var/www/public/index.html
      - ./logs:/var/log/nginx
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # working_dir: /work
